"""new db migrate

Revision ID: 2e69a39122cd
Revises: 46cf9ba29420
Create Date: 2026-01-13 11:35:10.772052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e69a39122cd'
down_revision = '46cf9ba29420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('auth_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_number', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('auth_file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auth_file_mime', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('auth_file_data', mysql.LONGBLOB(), nullable=True))
        batch_op.add_column(sa.Column('auth_reject_reasonn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auth_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_updated_at')
        batch_op.drop_column('auth_reject_reasonn')
        batch_op.drop_column('auth_file_data')
        batch_op.drop_column('auth_file_mime')
        batch_op.drop_column('auth_file_name')
        batch_op.drop_column('business_number')
        batch_op.drop_column('business_name')
        batch_op.drop_column('auth_status')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
