"""add description and tags to video

Revision ID: 3c668950a3d0
Revises: 2904edc8651f
Create Date: 2025-10-28 14:11:42.579258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c668950a3d0'
down_revision = '2904edc8651f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('description')

    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
