"""new db migrate

Revision ID: 609ec27e9448
Revises: b5e513a5b2da
Create Date: 2026-01-14 11:38:19.841211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '609ec27e9448'
down_revision = 'b5e513a5b2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
