"""new db migrate

Revision ID: 75f9824ce7c9
Revises: 5f994d0f42d7
Create Date: 2026-01-16 13:33:42.590696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75f9824ce7c9'
down_revision = '5f994d0f42d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_file_name')
        batch_op.drop_column('auth_file_data')
        batch_op.drop_column('auth_file_mime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_file_mime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('auth_file_data', mysql.LONGBLOB(), nullable=True))
        batch_op.add_column(sa.Column('auth_file_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
