"""image video 

Revision ID: 9318334b3ad8
Revises: e409b5358abb
Create Date: 2025-10-17 08:49:41.369827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9318334b3ad8'
down_revision = 'e409b5358abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_reason', sa.String(length=100), nullable=True))
        batch_op.drop_column('price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('applied_user_coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_coupons', ['applied_user_coupon_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pamphlet_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('pamphlet_mime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pamphlet_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discount_percent', sa.Integer(), nullable=True))
        batch_op.alter_column('base_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('pamphlet')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('video_mime', sa.String(length=50), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.drop_column('video_mime')
        batch_op.drop_column('video_data')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pamphlet', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.alter_column('base_price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('is_active')
        batch_op.drop_column('pamphlet_name')
        batch_op.drop_column('pamphlet_mime')
        batch_op.drop_column('pamphlet_data')
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('applied_user_coupon_id')
        batch_op.drop_column('is_read')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('discount_reason')
        batch_op.drop_column('discount_price')
        batch_op.drop_column('original_price')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
