"""register info

Revision ID: a83f6af7d3f0
Revises: 
Create Date: 2025-09-23 09:56:01.955294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a83f6af7d3f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('agree_terms', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agree_finance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agree_privacy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agree_age', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agree_marketing', sa.Boolean(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False))
        batch_op.drop_column('agree_marketing')
        batch_op.drop_column('agree_age')
        batch_op.drop_column('agree_privacy')
        batch_op.drop_column('agree_finance')
        batch_op.drop_column('agree_terms')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
