"""rename payment

Revision ID: e409b5358abb
Revises: e927b63d612c
Create Date: 2025-09-26 10:54:04.308952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e409b5358abb'
down_revision = 'e927b63d612c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.drop_column('payment')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pg_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_imp_uid'), ['imp_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_merchant_uid'), ['merchant_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_merchant_uid'))
        batch_op.drop_index(batch_op.f('ix_payments_imp_uid'))
        batch_op.alter_column('method',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('paid_at')
        batch_op.drop_column('pg_provider')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
