"""address update

Revision ID: e927b63d612c
Revises: 5eb4ef186c44
Create Date: 2025-09-24 10:10:11.137559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e927b63d612c'
down_revision = '5eb4ef186c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('detail_address', sa.String(length=200), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('detail_address')
        batch_op.drop_column('base_address')

    # ### end Alembic commands ###
