"""new user product column

Revision ID: f5fea8724b81
Revises: e7f3fa743b50
Create Date: 2025-12-26 13:40:11.947598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5fea8724b81'
down_revision = 'e7f3fa743b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_b2b_only', sa.Boolean(), nullable=True))

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_b2b_only')

    with op.batch_alter_table('advertisement_images', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
